name: Run Selenium Tests and Generate Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Set up ChromeDriver
        uses: actions/setup-chromedriver@v2
        with:
          chromedriver-version: 'latest'

      - name: Run Selenium tests and generate report
        run: npx mocha --reporter mochawesome --reporter-options reportDir=mochawesome-report,reportFilename=index,quiet=true

      - name: Upload Mochawesome report
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: mochawesome-report
