name: Run Selenium Tests and Generate Report

on:
  push:
    branches: [master]

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install mocha-junit-reporter
        run: npm install mocha-junit-reporter

      - name: Start server
        run: npm run dev &

      - name: Wait for server to start
        run: sleep 10

      - name: Install ChromeDriver
        run: npm install chromedriver

      # Генерация JUnit XML отчета
      - name: Run Selenium tests and generate JUnit XML report
        run: npx mocha test/timer.test.js --reporter mocha-junit-reporter --reporter-options mochaFile=results/mocha-test-results.xml

      # Загрузка результатов в Test IT
      - name: Submit results
        if: always()
        run: |
          pip install testit-cli
          testit results import \
            --url https://team-7lwe.testit.software \
            --project-id 0195bd40-8dbc-7dec-829d-705cfca339a9 \
            --configuration-id 15dbb164-c1aa-4cbf-830c-8c01ae14f4fb \
            --testrun-name "GitHub test run" \
            --results reports
        env:
          TMS_TOKEN: ${{ secrets.TESTIT_API_KEY }}
